### ISSUE TITLE
[Bug] Resolution failure for `create_table_as` macro when upgrading to 1.7.2

### ISSUE THREAD

**Issue by jeancochrane** [dbt-athena/dbt-athena#607]
### Is this a new bug in dbt-athena?

- [X] I believe this is a new bug in dbt-athena
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Our [dbt project](https://github.com/ccao-data/data-architecture/tree/master/dbt) compiles successfully when running `dbt-athena-community==1.7.1`:

```
(venv) ~/code/data-architecture/dbt$ dbt compile
17:04:41  Running with dbt=1.7.10
17:04:42  Registered adapter: athena=1.7.1
17:04:42  Found 78 models, 1 seed, 367 tests, 138 sources, 10 exposures, 0 metrics, 593 macros, 0 groups, 0 semantic models
17:04:42
17:04:45  Concurrency: 5 threads (target='dev')
17:04:45
```

However, upgrading to 1.7.2 causes a macro resolution error during compilation:

```
(venv) /code/data-architecture/dbt$ pip install -U dbt-athena-community==1.7.2
Collecting dbt-athena-community==1.7.2
  Using cached dbt_athena_community-1.7.2-py3-none-any.whl.metadata (40 kB)
...
Using cached dbt_athena_community-1.7.2-py3-none-any.whl (83 kB)
Installing collected packages: dbt-athena-community
  Attempting uninstall: dbt-athena-community
    Found existing installation: dbt-athena-community 1.7.1
    Uninstalling dbt-athena-community-1.7.1:
      Successfully uninstalled dbt-athena-community-1.7.1
Successfully installed dbt-athena-community-1.7.2
(venv) ~/code/data-architecture/dbt$ dbt compile
17:05:05  Running with dbt=1.7.10
17:05:05  Registered adapter: athena=1.7.2
17:05:05  Encountered an error:
Compilation Error
  In dispatch: No macro named 'create_table_as' found within namespace: 'athena'
      Searched for: 'athena.athena__create_table_as', 'athena.default__create_table_as', 'athena.athena__create_table_as', 'athena.default__create_table_as'
```

### Expected Behavior

I would expect there to be no difference in macro resolution during `dbt compile` between 1.7.1 and 1.7.2.

### Steps To Reproduce

This is how I reproduce the error on 1.7.2:

```
git clone git@github.com:ccao-data/data-architecture.git && cd data-architecture/dbt
cd dbt
python3 -m venv venv && source venv/bin/activate
pip install -U pip dbt-athena-community==1.7.2
dbt deps
dbt compile
```

Downgrade to 1.7.1 and confirm that the command succeeds:

```
pip install -U dbt-athena-community==1.7.1
dbt clean && dbt deps
dbt compile
```

This may not work for folks outside our org, though; I can try to pull together a minimal reproducible example if no one has seen this error before.

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS running in WSL on Windows 10
- Python: 3.10.12
- dbt: 1.7.10
- dbt-athena-community: 1.7.2
```

### Additional Context

It's totally possible there's just something wrong with my config, but it's strange to me that it worked on 1.6.4, continues to work on 1.7.1, but raises an error on 1.7.2. Let me know if you have thoughts on how I can debug this error and I'd be happy to try to figure out the root cause.
